[mysql]
# 数据库的连接信息，【最好root权限】
dsn = "root:123456@tcp(10.16.49.135:13306)/test?charset=utf8&parseTime=true&loc=Local"
# 数据库的明显
db = "test"
# 指定导出的表的名字
tables = ["cities", "provinces"]

[gocfg]
# 导出的模型的命名空间
namespace = "table"
# 导出的文件的路径
path = "table/table.go"
